import PDFDocument from 'pdfkit';
import { prisma } from './prisma';

export interface InvoiceItem {
  description: string;
  amount: number;
  quantity?: number;
}

export function buildInvoicePDFBuffer(params: {
  invoiceNumber: string;
  landlordName: string;
  tenantName?: string;
  propertyTitle?: string;
  propertyAddress?: string;
  type: string;
  amount: number;
  currency: string;
  status: string;
  dueDate: Date;
  paidAt?: Date | null;
  items: InvoiceItem[];
  notes?: string | null;
}) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks: Buffer[] = [];

  doc.on('data', (chunk: Buffer) => chunks.push(chunk));

  const currencySymbol = params.currency === 'NGN' ? '₦' : params.currency;
  const subtotal = params.items.reduce((sum, item) => sum + (item.amount * (item.quantity || 1)), 0);
  const total = params.amount;

  doc.fontSize(22).text('INVOICE', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).text(`Invoice #: ${params.invoiceNumber}`, { align: 'center' });
  doc.text(`Status: ${params.status.toUpperCase()}`, { align: 'center' });
  doc.moveDown();

  doc.text('FROM:');
  doc.font('Helvetica-Bold').text(params.landlordName);
  doc.font('Helvetica');
  doc.moveDown(0.5);

  if (params.tenantName) {
    doc.text('BILL TO:');
    doc.font('Helvetica-Bold').text(params.tenantName);
    doc.font('Helvetica');
    doc.moveDown(0.5);
  }

  if (params.propertyTitle) {
    doc.text(`Property: ${params.propertyTitle}`);
    if (params.propertyAddress) doc.text(`Address: ${params.propertyAddress}`);
    doc.moveDown(0.5);
  }

  doc.fontSize(14).text('Invoice Items', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(11);

  const tableTop = doc.y;
  const col1 = 50;
  const col2 = 320;
  const col3 = 420;

  doc.font('Helvetica-Bold');
  doc.text('Description', col1, tableTop);
  doc.text('Amount', col2, tableTop);
  doc.text('Total', col3, tableTop);
  doc.font('Helvetica');
  doc.moveDown(0.3);

  const rows: { description: string; amount: number; total: number }[] = params.items.map((item) => ({
    description: item.description,
    amount: item.amount,
    total: item.amount * (item.quantity || 1),
  }));

  for (const row of rows) {
    doc.text(row.description, col1);
    doc.text(`${currencySymbol}${row.amount.toLocaleString()}`, col2);
    doc.text(`${currencySymbol}${row.total.toLocaleString()}`, col3);
    doc.moveDown(0.3);
  }

  doc.moveDown();
  doc.font('Helvetica-Bold');
  doc.text(`Subtotal: ${currencySymbol}${subtotal.toLocaleString()}`, { align: 'right' });
  doc.text(`Total: ${currencySymbol}${total.toLocaleString()}`, { align: 'right' });
  doc.font('Helvetica');
  doc.moveDown();

  doc.text(`Due Date: ${params.dueDate.toLocaleDateString('en-NG')}`, { align: 'right' });
  if (params.paidAt) {
    doc.text(`Paid At: ${params.paidAt.toLocaleDateString('en-NG')}`, { align: 'right' });
  }
  doc.moveDown();

  if (params.notes) {
    doc.fontSize(10).text(`Notes: ${params.notes}`, { italics: true });
  }

  doc.moveDown(1);
  doc.fontSize(10).text('Generated by Propati', { align: 'center' });

  doc.end();

  return Buffer.concat(chunks);
}

export async function uploadInvoicePDF(params: {
  invoiceId: string;
  buffer: Buffer;
}): Promise<string> {
  const { uploadDocument } = await import('./cloudinary');
  const result = await uploadDocument(params.buffer, {
    folder: `propati/invoices/${params.invoiceId}`,
    public_id: `invoice-${params.invoiceId}`,
  });

  return result.secure_url;
}
